version: '3.8'
 
services:
  fastapi-app:
    container_name: login
    build: .
    image: fast_api_base
    ports:
      - "8000:8000"
    volumes:
      - .:/p-COPY-COPY
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:14.9
 
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5050:80
 
volumes:
  postgres_data: